alias git='hub'
alias wiki='e ~/Dropbox/Wikis'
alias cask="brew cask"
alias p='ps aux | grep'
alias rr="rackup -b \"run Rack::Directory.new '.'\""
alias reload='. ~/.zshrc'
alias eh='sudo vim /etc/hosts'
alias sj='e /usr/local/Cellar/jetty/8.1.8/libexec/contexts'
alias cleands='find . -name .DS_Store -type f -exec rm -v {} \;'
alias fixow='/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -r -domain local -domain user;killall Finder;echo "Open With has been rebuilt, Finder will relaunch"'
